spring:
   application: 
      name: springboot-consume-user
   datasource:
      name:shop
      url:jdbc:mysql://121.42.185.68:3306/shop?autoReconnect=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
      username:root
      password:wazll1314 
      type:com.alibaba.druid.pool.DruidDataSource
      driver-class-name:com.mysql.jdbc.Driver
      filters:stat
      maxActive:20
      initialSize:1
      maxWait:60000
      minIdle:1
      timeBetweenEvictionRunsMillis:6000
      minEvictableIdleTimeMillis:300000
      validationQuery:select 'x'
      testWhileIdle:true
      testOnBorrow:false
      testOnReturn:false
      poolPreparedStatements:true
      maxOpenPreparedStatements:20
   mybatis:
      mapperLocations:classpath:mapper/*.xml
      typeAliasesPackage:com.jiujichina.model 
eureka: 
  name: springProvideService
  client: 
    serviceUrl:
     defaultZone: http://www.jiujichina.com:8761/eureka/
     fetch-registery: true
     registry-fetch-interval-seconds: 30
  instance:
     prefer-ip-address: true
     lease-expiration-duration-in-seconds: 30
     lease-renewal-interval-in-seconds: 30
     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
   